# Generated by Django 4.0.4 on 2022-05-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Address_1',
        ),
        migrations.RemoveField(
            model_name='account',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='other_names',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='account',
            name='car',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='car'),
        ),
        migrations.AddField(
            model_name='account',
            name='details',
            field=models.CharField(max_length=60, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=60, null=True, verbose_name='username'),
        ),
    ]
