# Generated by Django 4.0.4 on 2022-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_address_1_remove_account_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='username'),
        ),
    ]
