# Generated by Django 4.0.4 on 2022-05-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Address_2',
        ),
    ]
