# Generated by Django 4.0.4 on 2022-05-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_address_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='car',
            field=models.CharField(max_length=60, null=True, verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='account',
            name='details',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='details'),
        ),
    ]
