# Generated by Django 4.0.4 on 2022-05-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_car_alter_account_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
    ]
