# Generated by Django 4.0.4 on 2022-05-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='account',
            new_name='user',
        ),
    ]
