# Generated by Django 4.0.4 on 2022-05-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
