# Generated by Django 4.0.4 on 2022-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0002_info_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True, verbose_name='type')),
                ('date', models.DateField(null=True, verbose_name='date')),
                ('number_plate', models.CharField(max_length=100, null=True, verbose_name='plate')),
                ('cost', models.IntegerField(null=True, verbose_name='cost')),
            ],
        ),
    ]
