# Generated by Django 4.0.4 on 2022-05-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0003_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='number_plate',
            field=models.CharField(max_length=100, null=True, verbose_name='Number Plate'),
        ),
    ]
