# Generated by Django 4.0.4 on 2022-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0004_alter_cars_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='cost',
            field=models.FloatField(null=True, verbose_name='cost'),
        ),
    ]
