# Generated by Django 3.2.12 on 2022-08-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0009_auto_20220829_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance',
            field=models.FloatField(null=True, verbose_name='balance'),
        ),
    ]
