# Generated by Django 3.2.12 on 2022-09-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0011_delete_completepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='number_plate',
            new_name='number_Plate',
        ),
    ]
