# Generated by Django 3.2.12 on 2022-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0012_rename_number_plate_cars_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='number_Plate',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Number Plate'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='type'),
        ),
    ]
